Repository jupyterlab/jupyterlab_server, pull requests merged in 2021-09, with the labels that each got.

#205 Translate settings schema
  jupyterlab_server/handlers.py
  jupyterlab_server/settings_handler.py
  jupyterlab_server/settings_utils.py
  jupyterlab_server/translation_utils.py
  jupyterlab_server/translations_handler.py
Labels: enhancement

#206 Automated Changelog Entry for 2.8.0 on master
  CHANGELOG.md
Labels: documentation

#207 Fall back to `DEFAULT_LOCALE` when translation settings schema is invalid in `get_current_locale`
  .gitignore
  jupyterlab_server/settings_handler.py
  jupyterlab_server/settings_utils.py
Labels: bug

#208 Automated Changelog Entry for 2.8.1 on master
  CHANGELOG.md
Labels: documentation

#210 Clean unneeded catch
  jupyterlab_server/settings_handler.py
Labels: bug

#213 Fallback to context-less translation on Python 3.7
  jupyterlab_server/translation_utils.py
Labels: bug

#214 Automated Changelog Entry for 2.8.2 on master
  CHANGELOG.md
Labels: documentation

#215 Clean up Readme
  README.md
Labels: documentation
