Repository jupyterlab/jupyterlab_server, pull requests merged in 2021-12, with the labels that each got.

#220 add page_config_hook
  jupyterlab_server/handlers.py
Labels: enhancement

#224 add overrides.d for settings defaults
  jupyterlab_server/settings_utils.py
  jupyterlab_server/tests/test_settings_api.py
Labels: enhancement

#222 pyproject.toml: clarify build system version
  pyproject.toml
Labels: enhancement

#225 Automated Changelog Entry for 2.9.0 on master
  CHANGELOG.md
Labels: documentation

#192 Delay list -> dict conversation to end
  jupyterlab_server/config.py
  jupyterlab_server/handlers.py
  jupyterlab_server/pytest_plugin.py
  jupyterlab_server/tests/test_labapp.py
Labels: bug

#227 Move workspace management in jupyterlab_server
  jupyterlab_server/__init__.py
  jupyterlab_server/handlers.py
  jupyterlab_server/workspaces_app.py
  jupyterlab_server/workspaces_handler.py
Labels: enhancement

#228 Automated Changelog Entry for 2.10.0 on main
  CHANGELOG.md
Labels: documentation

#229 Restore back older export for workspaces
  jupyterlab_server/__init__.py
  jupyterlab_server/workspaces_app.py
Labels: bug

#230 Automated Changelog Entry for 2.10.1 on main
  CHANGELOG.md
Labels: documentation

#232 Add downstream test workflow
  .github/workflows/downstream.yml
Labels: maintenance

#233 Fix issue where preferredPath is incorrectly calculated
  jupyterlab_server/handlers.py
Labels: bug

#234 Revert "Delay list -> dict conversation to end (#192)"
  jupyterlab_server/config.py
  jupyterlab_server/handlers.py
  jupyterlab_server/pytest_plugin.py
  jupyterlab_server/tests/test_labapp.py
Labels: bug

#235 Automated Changelog Entry for 2.10.2 on main
  CHANGELOG.md
Labels: documentation

#236 Fix workspace export without arguments
  jupyterlab_server/workspaces_app.py
Labels: bug
