Repository jupyterlab/jupyterlab_server, pull requests merged in 2021-08, with the labels that each got.

#194 PR: Update new_defaults dictionary instead of copy
  jupyterlab_server/settings_handler.py
  jupyterlab_server/tests/app-settings/overrides.json
  jupyterlab_server/tests/test_settings_api.py
Labels: bug

#195 Automated Changelog Entry for 2.6.2 on master
  CHANGELOG.md
Labels: documentation

#187 Switch to entrypoints package
  .gitignore
  jupyterlab_server/tests/test_translation_api.py
  jupyterlab_server/translation_utils.py
  setup.cfg
Labels: maintenance

#197 Automated Changelog Entry for 2.7.0 on master
  CHANGELOG.md
Labels: documentation

#198 TST: support openapi-core 0.14 SpecPath
  jupyterlab_server/tests/utils.py
  setup.cfg
Labels: maintenance

#199 Fix reset user settings if validation failed
  jupyterlab_server/settings_handler.py
Labels: bug

#200 Automated Changelog Entry for 2.7.1 on master
  CHANGELOG.md
Labels: documentation

#201 Use Check Links Action
  .github/workflows/tests.yml
  pyproject.toml
Labels: maintenance

#203 Recommend `pytest --pyargs jupyterlab_server`
  CONTRIBUTING.md
Labels: documentation

#202 Do not overwrite capitalization of region names
  jupyterlab_server/tests/test_translation_api.py
  jupyterlab_server/translation_utils.py
Labels: bug

#204 Automated Changelog Entry for 2.7.2 on master
  CHANGELOG.md
Labels: documentation
