Repository jupyterlab/jupyterlab_server, pull requests merged in 2022-03, with the labels that each got.

#239 Include Tests in Sdist But Not Wheel
  .github/workflows/downstream.yml
  .github/workflows/tests.yml
  MANIFEST.in
  jupyterlab_server/tests/conftest.py
  pyproject.toml
  setup.cfg
  tests/__init__.py
  tests/app-settings/overrides.json
  tests/conftest.py
  tests/schemas/@jupyterlab/apputils-extension/themes.json
  tests/schemas/@jupyterlab/codemirror-extension/commands.json
  tests/schemas/@jupyterlab/shortcuts-extension/package.json.orig
  tests/schemas/@jupyterlab/shortcuts-extension/plugin.json
  tests/schemas/@jupyterlab/translation-extension/plugin.json
  tests/schemas/@jupyterlab/unicode-extension/plugin.json
  tests/test_labapp.py
  tests/test_licenses_api.py
  tests/test_listings_api.py
  tests/test_settings_api.py
  tests/test_themes_api.py
  tests/test_translation_api.py
  tests/test_workspaces_api.py
  tests/translations/jupyterlab-language-pack-es_CO/MANIFEST.in
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/__init__.py
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab.json
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab.mo
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab.po
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.mo
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.po
  tests/translations/jupyterlab-language-pack-es_CO/setup.py
  tests/translations/jupyterlab-some-package/MANIFEST.in
  tests/translations/jupyterlab-some-package/jupyterlab_some_package/__init__.py
  tests/translations/jupyterlab-some-package/jupyterlab_some_package/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
  tests/translations/jupyterlab-some-package/setup.py
  tests/utils.py
  tests/workspaces/foo-2c26.jupyterlab-workspace
  tests/workspaces/foo-92dd.jupyterlab-workspace
Labels: maintenance

#241 Clean up CI
  .github/workflows/downstream.yml
  .github/workflows/tests.yml
  docs/environment.yml
  docs/source/api/handlers.rst
  pyproject.toml
  setup.cfg
Labels: maintenance

#242 Automated Changelog Entry for 2.11.0 on main
  CHANGELOG.md
Labels: documentation

#244 Automated Changelog Entry for 2.11.1 on main
  CHANGELOG.md
Labels: documentation

#245 Resolve paths in tests
  .github/workflows/tests.yml
  tests/test_translation_api.py
  tests/utils.py
Labels: bug

#246 Automated Changelog Entry for 2.11.2 on main
  CHANGELOG.md
Labels: documentation

#249 More CI Cleanup
  .github/workflows/downstream.yml
  .github/workflows/tests.yml
Labels: maintenance

#248 Adds notebook_starts_kernel option to make "canStartKernel" configurable
  jupyterlab_server/config.py
Labels: enhancement

#250 Updates parameter description for notebook_starts_kernel
  jupyterlab_server/config.py
Labels: documentation

#247 Clean up tests and add public openapi_spec
  jupyterlab_server/__init__.py
  jupyterlab_server/spec.py
  jupyterlab_server/test_utils.py
  setup.cfg
  tests/test_labapp.py
  tests/test_listings_api.py
  tests/test_settings_api.py
  tests/test_themes_api.py
  tests/test_translation_api.py
  tests/test_workspaces_api.py
Labels: enhancement

#252 Pin jinja for docs
  docs/environment.yml
  readthedocs.yml
Labels: maintenance

#255 update URLs, metadata, extras in setup.cfg
  setup.cfg
Labels: maintenance
