Repository jupyterlab/jupyterlab_server, pull requests merged in 2022-04, with the labels that each got.

#256 Add initial pre-commit
  .pre-commit-config.yaml
  CONTRIBUTING.md
  jupyterlab_server/config.py
  jupyterlab_server/handlers.py
  jupyterlab_server/process.py
  jupyterlab_server/process_app.py
  jupyterlab_server/server.py
  jupyterlab_server/settings_handler.py
  jupyterlab_server/settings_utils.py
  jupyterlab_server/test_utils.py
  jupyterlab_server/workspaces_handler.py
  tests/test_settings_api.py
  tests/test_workspaces_api.py
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab.json
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
  tests/translations/jupyterlab-some-package/jupyterlab_some_package/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
Labels: maintenance

#257 Apply Autoformats
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  RELEASE.md
  docs/autogen_config.py
  docs/environment.yml
  docs/source/conf.py
  jupyterlab_server/__init__.py
  jupyterlab_server/__main__.py
  jupyterlab_server/_version.py
  jupyterlab_server/app.py
  jupyterlab_server/config.py
  jupyterlab_server/handlers.py
  jupyterlab_server/licenses_app.py
  jupyterlab_server/licenses_handler.py
  jupyterlab_server/listings_handler.py
  jupyterlab_server/process.py
  jupyterlab_server/process_app.py
  jupyterlab_server/pytest_plugin.py
  jupyterlab_server/rest-api.yml
  jupyterlab_server/server.py
  jupyterlab_server/settings_handler.py
  jupyterlab_server/settings_utils.py
  jupyterlab_server/spec.py
  jupyterlab_server/templates/403.html
  jupyterlab_server/templates/index.html
  jupyterlab_server/test_data/app-settings/overrides.json
  jupyterlab_server/test_data/schemas/@jupyterlab/apputils-extension/themes.json
  jupyterlab_server/test_data/schemas/@jupyterlab/shortcuts-extension/plugin.json
  jupyterlab_server/test_utils.py
  jupyterlab_server/themes_handler.py
  jupyterlab_server/translation_utils.py
  jupyterlab_server/translations_handler.py
  jupyterlab_server/workspaces_app.py
  jupyterlab_server/workspaces_handler.py
  setup.py
  tests/conftest.py
  tests/test_labapp.py
  tests/test_licenses_api.py
  tests/test_listings_api.py
  tests/test_settings_api.py
  tests/test_themes_api.py
  tests/test_translation_api.py
  tests/test_workspaces_api.py
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab.json
  tests/translations/jupyterlab-language-pack-es_CO/jupyterlab_language_pack_es_CO/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
  tests/translations/jupyterlab-language-pack-es_CO/setup.py
  tests/translations/jupyterlab-some-package/jupyterlab_some_package/locale/es_CO/LC_MESSAGES/jupyterlab_some_package.json
  tests/translations/jupyterlab-some-package/setup.py
Labels: maintenance

#258 Add git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: maintenance

#261 Audit uses of print
  jupyterlab_server/handlers.py
  jupyterlab_server/settings_utils.py
  jupyterlab_server/workspaces_app.py
Labels: bug

#263 Make some pre-commit hooks manual
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
Labels: maintenance

#264 Switch to importlib.metadata to list entry points
  jupyterlab_server/translation_utils.py
  setup.cfg
Labels: maintenance

#267 Automated Changelog Entry for 2.13.0 on main
  CHANGELOG.md
Labels: documentation

#269 proper setup for the fallback logger
  jupyterlab_server/process.py
Labels: bug
