Repository jupyterlab/jupyterlab_server, pull requests merged in 2022-09, with the labels that each got.

#302 raise jupyter_server pin to include 2.x
  pyproject.toml
Labels: enhancement

#303 Automated Changelog Entry for 2.16.0rc0 on main
  CHANGELOG.md
Labels: documentation

#306 Clean up pyproject and ci
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  RELEASE.md
  jupyterlab_server/handlers.py
  jupyterlab_server/workspaces_handler.py
  pyproject.toml
Labels: maintenance

#308 Pin openapi_core dependency
  pyproject.toml
Labels: bug

#309 Automated Changelog Entry for 2.15.2 on 2.15.x
  CHANGELOG.md
Labels: documentation
