Repository jupyterlab/jupyterlab_server, pull requests merged in 2023-11, with the labels that each got.

#418 Clean up lint and ci
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#421 Update typings for server 2.10
  .pre-commit-config.yaml
  jupyterlab_server/pytest_plugin.py
  jupyterlab_server/settings_utils.py
  jupyterlab_server/workspaces_handler.py
Labels: maintenance

#417 Add repository info when getting federated extensions
  jupyterlab_server/config.py
Labels: bug

#422 Update ruff config
  .pre-commit-config.yaml
  pyproject.toml
Labels: maintenance

#423 Align JSON schema validator with one used on the frontend
  jupyterlab_server/settings_utils.py
Labels: maintenance

#424 Fix link-rot for Swagger view of OpenAPI spec
  jupyterlab_server/rest-api.yml
Labels: documentation

#425 Update typings for Server 2.10.1 and mypy 1.7
  .pre-commit-config.yaml
  jupyterlab_server/settings_utils.py
  jupyterlab_server/workspaces_handler.py
Labels: maintenance
