Repository jupyterlab/jupyterlab_server, pull requests merged in 2024-04, with the labels that each got.

#445 For v2 extensions parse entrypoint data
  jupyterlab_server/config.py
Labels: feature

#444 Ignore pageconfig file if JSON is zero-length
  jupyterlab_server/config.py
Labels: bug

#448 Add util to get consolidated page_config from higher levels
  jupyterlab_server/config.py
Labels: enhancement
