Repository jupyterlab/jupyterlab_server, pull requests merged in 2025-09, with the labels that each got.

#472 Fix CI Failures
  .github/workflows/codeql-analysis.yml
  .github/workflows/fix-license-header.yml
  .github/workflows/tests.yml
  jupyterlab_server/handlers.py
Labels: maintenance

#469 Add documentation for `page_config_hook`
  docs/source/api/handlers.rst
Labels: documentation

#471 Add `untracked_message_types` to Page Config
  jupyterlab_server/app.py
  jupyterlab_server/themes_handler.py
  jupyterlab_server/translation_utils.py
  tests/test_labapp.py
Labels: enhancement
